### ISSUE TITLE
Add Leopard support for "if on edge, bounce"

### ISSUE THREAD

**Issue by PullJosh** [leopard-js/sb-edit#78]
Leopard supports this but sb-edit does not translate it correctly.

**Comment by PullJosh** [comment]
Oops! Looks like I am wrong and this hasn't been merged into Leopard yet.

**Comment by adroitwhiz** [comment]
It looks like "if on edge, bounce" has [not yet been merged](https://github.com/leopard-js/leopard/pull/114).
