### ISSUE TITLE
Update sb-edit to latest TypeScript + new TypeScript idioms

### ISSUE THREAD

**Issue by adroitwhiz** [leopard-js/sb-edit#92]
TypeScript's undergone a lot of improvement since this project started. We could probably make use of a lot of new TS features in order to better infer and narrow types, especially for block inputs.

The way that people write TypeScript has also changed--for instance, TypeScript gained the `unknown` type, which represents a type that is a supertype of every other type. This replaces the unsafe `any` type, which can be used to violate type safety. Unfortunately, this codebase makes extensive use of `any`.

It's probably worth upgrading this project to use modern TypeScript. Since eliminating `any` could change the public API, it may be worth releasing a new major version?

**Comment by adroitwhiz** [comment]
![image](https://user-images.githubusercontent.com/25993062/221392384-ebbe2fef-8702-41ac-8647-1b1c006e9a5f.png)

my typescript-fu is too advanced :pensive:

**Comment by adroitwhiz** [comment]
![image](https://user-images.githubusercontent.com/25993062/221392413-83fa497c-ff57-4604-af88-33a1cd19a67a.png)

my typescript-fu is too silly :pensive:

**Comment by towerofnix** [comment]
Thanks! This is something to investigate, for sure — sb-edit is my main exposure to TypeScript, honestly, so I'm not versed in any recent additions. 😅

I'll mark here the existing `(block.inputs.VARIABLE.value as { id: string }).id` pattern [mentioned here](https://github.com/leopard-js/sb-edit/pull/89/files#r1118010579). There are plenty of other examples of casting "assumptions" about block inputs which TypeScript isn't picking up on (or, you know, is correctly warning us about in the case of arbitrarily shaped inputs from unknown blocks!).
