### ISSUE TITLE
toSb3: "change pen (color) by" errors out when serializing

### ISSUE THREAD

**Issue by adroitwhiz** [leopard-js/sb-edit#97]
It looks like we name one input `colorParam` instead of `COLOR_PARAM`. I noticed this when trying to strictly type the Scratchblocks output for the strict TypeScript PR.

**Comment by towerofnix** [comment]
Oh wow, can you check if this makes rendering at least do anything (rather than black screen) in the project linked in leopard-js/leopard#162? It's possible it's unrelated, but this seems like the kind of mistake which would cause a block to unintentionally no-op without visible error.

**Comment by adroitwhiz** [comment]
Probably not--the Leopard export works but the SB3 export was broken.
